local width, height = getSize()
paintutils.drawPixel(2, 0, colors.yellow)
paintutils.drawPixel(width - 1, 2, colors.yellow)
paintutils.drawPixel(5, 2, colors.orange)
paintutils.drawPixel(width - 2, 2, colors.orange)
paintutils.drawPixel(6, 2, colors.orange)
paintutils.drawPixel(width - 3, 2, colors.orange)
paintutils.drawPixel(9, 2, colors.orange)
paintutils.drawPixel(width - 6, 2, colors.orange)
paintutils.drawPixel(10, 2, colors.orange)
paintutils.drawPixel(width - 7, 2, colors.orange)
paintutils.drawPixel(14, 2, colors.orange)
paintutils.drawPixel(width - 11, 2, colors.orange)
paintutils.drawPixel(15, 2, colors.orange)
paintutils.drawPixel(width - 12, 2, colors.orange)
paintutils.drawPixel(23, 2, colors.orange)
paintutils.drawPixel(width - 20, 2, colors.orange)
paintutils.drawPixel(0, 1, colors.yellow)
paintutils.drawPixel(width - -1, 3, colors.yellow)
paintutils.drawPixel(6, 3, colors.orange)
paintutils.drawPixel(width - 3, 3, colors.orange)
paintutils.drawPixel(6, 1, colors.yellow)
paintutils.drawPixel(width - 5, 3, colors.yellow)
paintutils.drawPixel(10, 3, colors.orange)
paintutils.drawPixel(width - 7, 3, colors.orange)
paintutils.drawPixel(14, 3, colors.orange)
paintutils.drawPixel(width - 11, 3, colors.orange)
paintutils.drawPixel(13, 1, colors.yellow)
paintutils.drawPixel(width - 12, 3, colors.yellow)
paintutils.drawPixel(16, 3, colors.orange)
paintutils.drawPixel(width - 13, 3, colors.orange)
paintutils.drawPixel(15, 1, colors.yellow)
paintutils.drawPixel(width - 14, 3, colors.yellow)
paintutils.drawPixel(18, 3, colors.orange)
paintutils.drawPixel(width - 15, 3, colors.orange)
paintutils.drawPixel(19, 3, colors.orange)
paintutils.drawPixel(width - 16, 3, colors.orange)
paintutils.drawPixel(20, 3, colors.orange)
paintutils.drawPixel(width - 17, 3, colors.orange)
paintutils.drawPixel(19, 1, colors.yellow)
paintutils.drawPixel(width - 18, 3, colors.yellow)
paintutils.drawPixel(22, 3, colors.orange)
paintutils.drawPixel(width - 19, 3, colors.orange)
paintutils.drawPixel(24, 3, colors.orange)
paintutils.drawPixel(width - 21, 3, colors.orange)
paintutils.drawPixel(26, 3, colors.orange)
paintutils.drawPixel(width - 23, 3, colors.orange)
paintutils.drawPixel(28, 3, colors.orange)
paintutils.drawPixel(width - 25, 3, colors.orange)
paintutils.drawPixel(2, 4, colors.orange)
paintutils.drawPixel(width - -1, 4, colors.orange)
paintutils.drawPixel(4, 4, colors.orange)
paintutils.drawPixel(width - 1, 4, colors.orange)
paintutils.drawPixel(5, 2, colors.yellow)
paintutils.drawPixel(width - 4, 4, colors.yellow)
paintutils.drawPixel(10, 4, colors.orange)
paintutils.drawPixel(width - 7, 4, colors.orange)
paintutils.drawPixel(15, 4, colors.orange)
paintutils.drawPixel(width - 12, 4, colors.orange)
paintutils.drawPixel(23, 4, colors.orange)
paintutils.drawPixel(width - 20, 4, colors.orange)
paintutils.drawPixel(3, 5, colors.orange)
paintutils.drawPixel(width - 0, 5, colors.orange)
paintutils.drawPixel(5, 5, colors.orange)
paintutils.drawPixel(width - 2, 5, colors.orange)
paintutils.drawPixel(6, 5, colors.orange)
paintutils.drawPixel(width - 3, 5, colors.orange)
paintutils.drawPixel(7, 5, colors.orange)
paintutils.drawPixel(width - 4, 5, colors.orange)
paintutils.drawPixel(8, 5, colors.orange)
paintutils.drawPixel(width - 5, 5, colors.orange)
paintutils.drawPixel(7, 3, colors.yellow)
paintutils.drawPixel(width - 6, 5, colors.yellow)
paintutils.drawPixel(10, 5, colors.orange)
paintutils.drawPixel(width - 7, 5, colors.orange)
paintutils.drawPixel(9, 3, colors.yellow)
paintutils.drawPixel(width - 8, 5, colors.yellow)
paintutils.drawPixel(12, 5, colors.orange)
paintutils.drawPixel(width - 9, 5, colors.orange)
paintutils.drawPixel(13, 5, colors.orange)
paintutils.drawPixel(width - 10, 5, colors.orange)
paintutils.drawPixel(14, 5, colors.orange)
paintutils.drawPixel(width - 11, 5, colors.orange)
paintutils.drawPixel(2, 6, colors.orange)
paintutils.drawPixel(width - -1, 6, colors.orange)
paintutils.drawPixel(7, 6, colors.orange)
paintutils.drawPixel(width - 4, 6, colors.orange)
paintutils.drawPixel(11, 6, colors.orange)
paintutils.drawPixel(width - 8, 6, colors.orange)
paintutils.drawPixel(2, 7, colors.orange)
paintutils.drawPixel(width - -1, 7, colors.orange)
paintutils.drawPixel(3, 7, colors.orange)
paintutils.drawPixel(width - 0, 7, colors.orange)
paintutils.drawPixel(4, 7, colors.orange)
paintutils.drawPixel(width - 1, 7, colors.orange)
paintutils.drawPixel(5, 7, colors.orange)
paintutils.drawPixel(width - 2, 7, colors.orange)
paintutils.drawPixel(4, 5, colors.yellow)
paintutils.drawPixel(width - 3, 7, colors.yellow)
paintutils.drawPixel(7, 7, colors.orange)
paintutils.drawPixel(width - 4, 7, colors.orange)
paintutils.drawPixel(6, 5, colors.yellow)
paintutils.drawPixel(width - 5, 7, colors.yellow)
paintutils.drawPixel(7, 5, colors.yellow)
paintutils.drawPixel(width - 6, 7, colors.yellow)
paintutils.drawPixel(12, 7, colors.orange)
paintutils.drawPixel(width - 9, 7, colors.orange)
paintutils.drawPixel(3, 6, colors.yellow)
paintutils.drawPixel(width - 2, 8, colors.yellow)
paintutils.drawPixel(7, 8, colors.orange)
paintutils.drawPixel(width - 4, 8, colors.orange)
paintutils.drawPixel(7, 6, colors.yellow)
paintutils.drawPixel(width - 6, 8, colors.yellow)
paintutils.drawPixel(10, 8, colors.orange)
paintutils.drawPixel(width - 7, 8, colors.orange)
paintutils.drawPixel(11, 8, colors.orange)
paintutils.drawPixel(width - 8, 8, colors.orange)
paintutils.drawPixel(12, 8, colors.orange)
paintutils.drawPixel(width - 9, 8, colors.orange)
paintutils.drawPixel(0, 7, colors.yellow)
paintutils.drawPixel(width - -1, 9, colors.yellow)
paintutils.drawPixel(3, 9, colors.orange)
paintutils.drawPixel(width - 0, 9, colors.orange)
paintutils.drawPixel(7, 9, colors.orange)
paintutils.drawPixel(width - 4, 9, colors.orange)
paintutils.drawPixel(9, 7, colors.yellow)
paintutils.drawPixel(width - 8, 9, colors.yellow)
paintutils.drawPixel(13, 9, colors.orange)
paintutils.drawPixel(width - 10, 9, colors.orange)
paintutils.drawPixel(15, 9, colors.orange)
paintutils.drawPixel(width - 12, 9, colors.orange)
paintutils.drawPixel(14, 7, colors.yellow)
paintutils.drawPixel(width - 13, 9, colors.yellow)
paintutils.drawPixel(2, 10, colors.orange)
paintutils.drawPixel(width - -1, 10, colors.orange)
paintutils.drawPixel(2, 8, colors.yellow)
paintutils.drawPixel(width - 1, 10, colors.yellow)
paintutils.drawPixel(6, 10, colors.orange)
paintutils.drawPixel(width - 3, 10, colors.orange)
paintutils.drawPixel(3, 11, colors.orange)
paintutils.drawPixel(width - 0, 11, colors.orange)
paintutils.drawPixel(4, 11, colors.orange)
paintutils.drawPixel(width - 1, 11, colors.orange)
paintutils.drawPixel(5, 11, colors.orange)
paintutils.drawPixel(width - 2, 11, colors.orange)
paintutils.drawPixel(13, 11, colors.orange)
paintutils.drawPixel(width - 10, 11, colors.orange)
paintutils.drawPixel(2, 10, colors.yellow)
paintutils.drawPixel(width - 1, 12, colors.yellow)
paintutils.drawPixel(11, 10, colors.yellow)
paintutils.drawPixel(width - 10, 12, colors.yellow)
paintutils.drawPixel(4, 13, colors.orange)
paintutils.drawPixel(width - 1, 13, colors.orange)
paintutils.drawPixel(4, 14, colors.orange)
paintutils.drawPixel(width - 1, 14, colors.orange)
paintutils.drawPixel(2, 13, colors.yellow)
paintutils.drawPixel(width - 1, 15, colors.yellow)
paintutils.drawPixel(4, 16, colors.orange)
paintutils.drawPixel(width - 1, 16, colors.orange)
paintutils.drawPixel(3, 17, colors.orange)
paintutils.drawPixel(width - 0, 17, colors.orange)
paintutils.drawPixel(5, 17, colors.orange)
paintutils.drawPixel(width - 2, 17, colors.orange)
paintutils.drawPixel(4, 18, colors.orange)
paintutils.drawPixel(width - 1, 18, colors.orange)
paintutils.drawPixel(4, 20, colors.orange)
paintutils.drawPixel(width - 1, 20, colors.orange)
